[service]
id = "web-alpha"
name = "web-alpha"
port = 9000

[mongoose.test]
uri = "mongodb://0.0.0.0:27017/test"

[mongoose.commons]
uri = "mongodb://0.0.0.0:27017/commons"

[supplier.iam]
host = "http://localhost:3001"

[supplier.user]
host = "http://localhost:3003"

[jwt]
secret = "lnferno"
refreshSecret = "lnferno"
expiresIn = "1h"
refreshExpiresIn = "1h"