[service]
id = "boilerplate"
name = "boilerplate"
port = 9000

[mongoose.test]
uri = "mongodb://0.0.0.0:27017/test"

[mongoose.commons]
uri = "mongodb://0.0.0.0:27017/commons"

[provider.user]
host = "http://localhost:9000/test"